package kz.kbtu.tsis5v2.enums;

public enum School {
    SCHOOL_OF_COMPUTING_AND_INFORMATICS,
    SCHOOL_OF_BUSINESS_AND_MANAGEMENT,
    SCHOOL_OF_ENGINEERING_AND_TECHNOLOGY,
    SCHOOL_OF_HUMANITIES_AND_SOCIAL_SCIENCES,
    SCHOOL_OF_LAW_AND_POLITICAL_SCIENCE
}
